name: restaurantapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  google_fonts:
  provider:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sushi (1).png
    - assets/images/sushi (2).png
    - assets/images/sushi (3).png
    - assets/images/sushi.png
